# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3306/job_winner
spring.r2dbc.username=root
spring.r2dbc.password=1234

# Flyway
spring.flyway.url=jdbc:mysql://localhost:3306/job_winner
spring.flyway.user=root
spring.flyway.password=1234
spring.flyway.locations=classpath:db/migration-mysql

# Frontend
ui.path=http://localhost:3000
